### ISSUE TITLE
webpack.config.js specifies wrong tsconfig.webpack.json

### ISSUE THREAD

**Issue by Nicolletta** [aefox/intra-hq#14]
webpack.config.js contains:
```
{  
   test: /\.tsx?$/,
   loaders: ["babel-loader?cacheDirectory", "awesome-typescript-loader?tsconfig=tsconfig.webpack.json&useCache=true"]
}
```
The **tsconfig=tsconfig.webpack.json** isn't part of the project. Instead we have **tconfig.webpack.json**. And also the parameter name in the loader is wrong, should be something like:
`configFileName=tconfig.webpack.json`

**Comment by aefox** [comment]
closing this as we switched to ![create-react-app](https://github.com/facebookincubator/create-react-app) and this no longer applies
