### ISSUE TITLE
Missing styles from storybook

### ISSUE THREAD

**Issue by banarualexandru** [aefox/intra-hq#2]
There's no styles in storybook.
![image](https://user-images.githubusercontent.com/7972978/27537237-9a74b28e-5a7b-11e7-8a83-450b63f84390.png)
In app styles applied ok.
![image](https://user-images.githubusercontent.com/7972978/27537251-af74b7d8-5a7b-11e7-9c90-c03c72c95c48.png)

**Comment by aefox** [comment]
closing this as we switched to ![create-react-app](https://github.com/facebookincubator/create-react-app) and this no longer applies
