### ISSUE TITLE
Problems in rendering images

### ISSUE THREAD

**Issue by Nicolletta** [aefox/intra-hq#3]
It works in case you specify something like "./**src**/components/logoCGK.png"

**Comment by aefox** [comment]
closing this as we switched to ![create-react-app](https://github.com/facebookincubator/create-react-app) and this no longer applies (at least in theory). if it resurfaces we can reopen this

for extra info see ![this file](https://github.com/aefox/intra-hq/commit/58ff64085e72e5802e04b3c43d7cc8852e7a6907#diff-ac3c50ae15a631981374f09a64815339)
