### ISSUE TITLE
Could not load images

### ISSUE THREAD

**Issue by chuleva** [aefox/intra-hq#5]
import * as React from "react";
import url from "../logo.png"; // compilation TS2307: Cannot find module '../logo.png'.

export default (props, { }) => {
  return (
    <div>
      <img src={url} alt="" />
      <button type="button" className="btn">Search</button>
    </div>
  );
};

**Comment by chuleva** [comment]
Working in progress

**Comment by aefox** [comment]
closing this as we switched to ![create-react-app](https://github.com/facebookincubator/create-react-app) and this no longer applies. see ![this file](https://github.com/aefox/intra-hq/commit/58ff64085e72e5802e04b3c43d7cc8852e7a6907#diff-ac3c50ae15a631981374f09a64815339)
